version: "3.8"
services:
  #
  backend:
    build: ./healph-backend
    container_name: healph-backend
    image: node:16.20.0-alpine
    #restart: always
    ports:
      - "3000:3000"
    working_dir: /healph-backend/
    entrypoint: ["npm", "start"]
    networks:
      - healph-net
#connecting each container
networks:
  healph-net:
    driver: bridge


#docker-compose build
#docker-compose up